version: '3.8'

services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/studymind
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    networks:
      - studymind-network
    restart: unless-stopped

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - studymind-network
    restart: unless-stopped

networks:
  studymind-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
